a = 10
b = 20

print("a == b:", a == b)
print("a != b:", a != b)
print("a > b:", a > b)
print("a < b:", a < b)
print("a >= b:", a >= b)
print("a <= b:", a <= b)
print("is", a is b)
print("is not", a is not b)
print("a and b:", a and b)
print("a or b:", a or b)
print("not a:", not a)
print("not b:", not b)
print("a & b:", a & b)
print("a | b:", a | b)
print("a ^ b:", a ^ b)
print("a << b:", a << b)
print("a >> b:", a >> b)
print("a // b:", a // b)
print("a ** b:", a ** b)
print("a % b:", a % b)