fruits = ["apple", "banana", "cherry"]  

print(fruits)
print(fruits[0]) 
print(fruits[1])
print(fruits[2])
print("\n ")
print(fruits[-1])
print(fruits[-2])
print(fruits[-3])
print("\n ")
print(fruits[0:2])
print(fruits[1:3])
print(fruits[:2])
print(fruits[1:])
print(fruits[-2:])
print("\n ")
print(len(fruits))
print(fruits[1:3])
